version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "e2e"
      - "github_actions"

  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    labels:
      - "dependencies"
      - "e2e"
      - "javascript"
