name: Package Action

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'
  workflow_dispatch:

jobs:
  package:
    name: Package dist files
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      # Output logs to file in case we need to inspect errors.
      GITSIGN_LOG: "/tmp/gitsign.log"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.x

      - name: Deps
        run: |
          npm ci

      - name: Package
        run: |
          npm run build
          npm run package

      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: Commit Dist
        run: |
          git config --global user.email ${{ secrets.RHACS_BOT_GITHUB_EMAIL }}
          git config --global user.name ${{ secrets.RHACS_BOT_GITHUB_USERNAME }}
          git add dist
          git commit -m "chore: Update dist" || echo "No changes to commit."
          git push origin
